IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "CA1"
    
    config.vm.network "private_network", ip: "192.168.56.10"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
    end
    
    config.vm.provision :shell, path: "bootstrap.sh"
end