IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "docker-base"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
    end

    config.vm.provision :shell, path: "install.sh"
end