IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "CA1"
    
    config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2

        vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", File.expand_path("~/VirtualBox VMs/ubuntu.vdi")]
    end
    
    config.vm.provision :shell, inline: <<-EOF
        #!/bin/bash

        # change the apt source to iran
        sed -i 's|http://us.|http://ir.|g' /etc/apt/sources.list

        # set my ssh key
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEZ23Ckrz+7PA7T8+2ps1dcREPui1KABCs8tbpZ6E42 mvajhi@mahdi-laptop" >> /home/vagrant/.ssh/authorized_keys
    EOF
end