apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 0.5G
            memory: 1G
          requests:
            cpu: "0.5"
            ephemeral-storage: 0.5G
            memory: 1G